### ISSUE TITLE
Reduce text brightness in reading mode

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#124]
I hope the text brightness is reduced in reading mode, for the comfort of the eyes

![Screenshot_٢٠٢٢٠٨٢٨_١٠١٨٣١](https://user-images.githubusercontent.com/38974362/187083833-4a202f3e-1d9a-4865-a7f3-e105e976adf2.png)

**Comment by alialbaali** [comment]
Do you think there should be an option to choose dim amount, with a slider?

**Comment by AI-IMED** [comment]
If this will include the editing mode as well, I think that having the option will be useful, but if the matter will be limited to the reading mode, I prefer that you adjust the brightness value that you see fit and comfortable for reading yourself, without the need to add an option

**Comment by AI-IMED** [comment]
v2.2.0-Beta2
The dim is too high for me, I don't see anything when I'm in a bright place especially when I use the dark and black theme, the idea of ​​having a bar to control the opacity level seems really useful.

**Comment by alialbaali** [comment]
Would you prefer a few modes such as (Low, Mid, High), or a complete brightness bar?

**Comment by AI-IMED** [comment]
I think the bar is better, because it allows more flexibility in controlling the amount of brightness

**Comment by alialbaali** [comment]
Both can be shown as bars. It's just about the amount of options available. One is just like the bar in your device that controls the brightness, and the other provides 3 to 5 options in a bar or a dialog.

**Comment by AI-IMED** [comment]
If you mean a bar that looks like a control bar for the number of lines in the previews, with numbers replaced with the names of the options in the dialog boxes and without skipping some values ​​between each two options, this is fine, and if indeed there will be some values ​​ignored between each two options, then the full brightness bar will certainly be  better

I was thinking instead of all that, with a gesture that takes advantage of the part shown in the picture, this way the control is faster and easi

![Screenshot_٢٠٢٢٠٩١٣_٠٧٤٥٣٩](https://user-images.githubusercontent.com/38974362/189829859-c8750312-cf4a-485d-a203-3c0ef2b657de.png)

**Comment by alialbaali** [comment]
I don't agree with adding a bar in Reading Mode, due to these reasons:

1. It would replicate the same bar in the Notification Panel.
2. It would be enabled always.
3. The placement you have provided isn't the best UX/UI.

I personally prefer to have **quick** options available to the user, without messing with the UI much. This is what I came up with:
![IMAGE 2022-09-13 14:29:38](https://user-images.githubusercontent.com/37933889/189889934-7797ab69-d3d6-4b15-8205-c0c5f0a1843d.jpg)

There could be an option at the end, to set a custom value using the bar. Also, these options could also be modified from Reading Mode screen itself displayed as an icon.

**Comment by AI-IMED** [comment]
Well, I have to wait, maybe the experience is better than I imagined

**Comment by AI-IMED** [comment]
It's okay. Thanks.
