### ISSUE TITLE
[Proposal] Exchange Select and Reminder buttons

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#136]
It would be more obvious (and smarter and slicker to operate), if the Select and the Reminder buttons would exchange their positions in the note options drawer. Not only is the Select tool hidden and needs the user to do one more action, firstly pull the drawer open, it is probably also much more often utilised by the majority of users as it opens up many more subsequent operations.

**Comment by alialbaali** [comment]
I thought about moving the select button first thing at the top. However, I also thought about adding an edit button at the same place (at the top), that's why the Select button is currently at the bottom.

The reason I thought about adding an edit button, is that, when notes open in Reading Mode by default, the user might want to edit the note sometimes rather than opening it in Reading Mode.

I'm hesitant about this decision, because there's already an edit button in Reading Mode itself.

What do you think?

**Comment by uli-on** [comment]
Sorry, I'm confused: Firstly, where do I find the Open In Reading Mode By Default toggle in beta 2? Or is your question about two hypothetical options at once?

**Comment by uli-on** [comment]
Currently we're having a Reading Mode button in the note options drawer when your choice in folder options is reading mode already. Would what you're asking not simply be a continuation of the duplicate options? If so, I'd opt for a select button there, instead. 
But another possibility we're to keep the Select button full width and that way make it more visible, make it easier to tap, and stress the significance of this new function.

**Comment by uli-on** [comment]
Yup, less confusing, less redundancy.

**Comment by uli-on** [comment]
I'm afraid the last discussion here above led away from my initial proposal to make the "Select" button more visible...
