### ISSUE TITLE
Problem with import in Noto app

### ISSUE THREAD

**Issue by maxongshD** [alialbaali/Noto#220]
when you select a file to import, the application crashes and shows a "list of changes" and at the bottom there is a notification "import successful"
[video with problem:](https://wdfiles.ru/LI3h)

**Comment by alialbaali** [comment]
Thank you for providing me with the screen recording. The reason it's not working, is because you're trying to import different files which are not suitable (or work) for Noto. The _import_ feature can only be used with the files that Noto produces using the _Export_ feature, and not any other file. 

Try to write some notes, label them, and add them to folders. Then you can export them using the _Export_ button, and import them back again using the _Import_ button. 

This feature is used as a backup **only**, and not as a migration tool from other note apps.

Please try what I mentioned above, and let me know if you find issues!

**Comment by maxongshD** [comment]
okay, i understand. thank you friend, for helping me. 
Noto - best app for notes. simple and aesthetic style design.
